# Generated by Django 4.1.7 on 2023-03-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='useremail',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
