# this setting is only required for older version of django like 2.0... from 2.1 version it is automatically configured...
# since here in this project we use django 4.1.4 so we dont need to do this settings...


# if we using any other database then we dont need to do this settings...

# for connecting the mysql database with django we need to do this setting in main project init.py......
# pip install pymysql
# import pymysql
# pymysql.install_as_MySQLdb()
