# Generated by Django 4.2 on 2023-04-12 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(default=None, max_length=2500, null=True, upload_to='user_memories/')),
                ('about', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
