# Generated by Django 4.1.7 on 2023-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellist',
            name='image',
            field=models.FileField(default=None, max_length=2500, null=True, upload_to='image_folder_postgree/'),
        ),
    ]
