# Generated by Django 4.1.7 on 2023-03-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookinghotel_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghotel',
            name='no_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='useremail',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
