# Generated by Django 4.1.7 on 2023-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookinghotel_no_rooms_bookinghotel_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghotel',
            name='userpassword',
            field=models.CharField(max_length=200),
        ),
    ]
